version: '3'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "${GPU_COUNT:-1}"
              capabilities: [gpu]

volumes:
  ollama:
